### ISSUE TITLE
deprecated attributes warnings

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/homebrew-amiaos#128]
When attempting to reinstall QCTools (which I was prompted to do when opening the program), I received the following warnings:
```

Last login: Wed Sep 12 13:28:10 on ttys000
mac2:~ mac2$ brew install amiaopensource/amiaos/qctools
==> Installing qctools from amiaopensource/amiaos
==> Downloading https://github.com/bavc/qctools/archive/v0.9.tar.gz
Already downloaded: /Users/mac2/Library/Caches/Homebrew/downloads/e99fb9799bb66e37bce600e5aa70d580676713cfdb270812f9a38cbcf435211f--qctools-0.9.tar.gz
==> qmake qctools-lib.pro
==> make
Last 15 lines from /Users/mac2/Library/Logs/Homebrew/qctools/02.make:
../../../Source/Core/CommonStreamStats.cpp:169:5: warning: field 'start_time' will be initialized after field 'codec_time_base' [-Wreorder]
    start_time(stream != NULL ? std::to_string(stream->start_time * av_q2d(stream->time_base)) : ""),
    ^
../../../Source/Core/CommonStreamStats.cpp:211:5: warning: 'av_get_codec_tag_string' is deprecated [-Wdeprecated-declarations]
    av_get_codec_tag_string(val_str, sizeof(val_str), codec_tag);
    ^
/usr/local/Cellar/ffmpeg/4.0.2/include/libavcodec/avcodec.h:5549:1: note: 'av_get_codec_tag_string' has been explicitly marked deprecated here
attribute_deprecated
^
/usr/local/Cellar/ffmpeg/4.0.2/include/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
9 warnings generated.
2 warnings generated.
6 warnings generated.
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/amiaopensource/homebrew-amiaos/issues
```

**Comment by retokromer** [comment]
The problem seems still to subsist:

![screen shot 2018-11-06 at 08 15 13](https://user-images.githubusercontent.com/3246607/48073155-68ada580-e1de-11e8-9ca2-f979f9d3d116.png)

**Comment by retokromer** [comment]
The problem is resolved now, but my [pull request](https://github.com/amiaopensource/homebrew-amiaos/pull/130) has not been considered, therefore I wrote in an [alternate formula](https://github.com/AVpres/homebrew-formulae/blob/master/qctools-x.rb).

**Comment by kieranjol** [comment]
Shouldn't this be reopened as the issue is not resolved in the official homebrew?

**Comment by retokromer** [comment]
The pull request was open for almost two months…

**Comment by dericed** [comment]
Sorry to not reply here earlier. Qctools 1.0 is supported by “brew cask install qctools” and the qctools maintainers help support that in homebrew-cask. The referenced installer is a tap while homebrew recommends gui installers use cask installs and not this method. I would suggest removing the referenced installer in favor of the cask one and that I remove he reference to it from qctools documentation.

**Comment by retokromer** [comment]
Then should we delete the formula here?

**Comment by retokromer** [comment]
Just made the [PR](https://github.com/amiaopensource/homebrew-amiaos/pull/142) for deleting.

**Comment by retokromer** [comment]
I also made a [PR](https://github.com/bavc/qctools/pull/575) for this part of the documentation.

@dericed Please update also the developer build installation. Thank you!
